start:
  description: Send a raw packet to device.
  fields:
    entity_id: 
      description: Name of entity of the cast media player you want to play Spotify from.
      example: 'media_player.livingroom'
    device_name:
      description: Name of the Cast Device
      example: Livingroom
    uri: 
      description: Supported Spotify URI as string, array not supported.
